### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by HypePickups** [amitasviper/Auto-CAS-Login-ChromeExtension#1]
I am sort of confused on what this does. A better explanation would be better I am trying to make a chrome extension with a login that takes in one time use tokens. where I can sell them on my website and email the person the token. then they use the email and the token they recieved to log into my chrome extension.  But I am really struggling on how I would do this. ANy help is apreciated.

**Comment by amitkumarusc** [comment]
This extension was created for my personal use. It basically clicks on a button on a webpage which takes you to a form containing the `username` field and `One-time password` field and then generates a new OTP and submits the forms. The username and secret key used to generate the OPT can be entered by clicking the extension icon.

The [token_generator.js](https://github.com/amitasviper/Auto-CAS-Login-ChromeExtension/blob/master/token_generator.js) file has the code to generate the OTP code. You can reuse that code in your application if you want. The websites on which this extension will run can be controlled using the `manifest.json` file
